// Code generated by go-bindata.
// sources:
// tests/partial.mustache
// tests/test1.mustache
// tests/test2.mustache
// tests/test3.mustache
// DO NOT EDIT!

package mustache

import (
	"bytes"
	"compress/gzip"
	"fmt"
	"io"
	"strings"
	"os"
	"time"
	"io/ioutil"
	"path/filepath"
)

func bindataRead(data []byte, name string) ([]byte, error) {
	gz, err := gzip.NewReader(bytes.NewBuffer(data))
	if err != nil {
		return nil, fmt.Errorf("Read %q: %v", name, err)
	}

	var buf bytes.Buffer
	_, err = io.Copy(&buf, gz)
	clErr := gz.Close()

	if err != nil {
		return nil, fmt.Errorf("Read %q: %v", name, err)
	}
	if clErr != nil {
		return nil, err
	}

	return buf.Bytes(), nil
}

type asset struct {
	bytes []byte
	info  os.FileInfo
}

type bindataFileInfo struct {
	name string
	size int64
	mode os.FileMode
	modTime time.Time
}

func (fi bindataFileInfo) Name() string {
	return fi.name
}
func (fi bindataFileInfo) Size() int64 {
	return fi.size
}
func (fi bindataFileInfo) Mode() os.FileMode {
	return fi.mode
}
func (fi bindataFileInfo) ModTime() time.Time {
	return fi.modTime
}
func (fi bindataFileInfo) IsDir() bool {
	return false
}
func (fi bindataFileInfo) Sys() interface{} {
	return nil
}

var _partialMustache = []byte("\x1f\x8b\x08\x00\x00\x09\x6e\x88\x00\xff\xaa\xae\xf6\x4b\xcc\x4d\xad\xad\x05\x04\x00\x00\xff\xff\xb0\xcf\x02\xd8\x08\x00\x00\x00")

func partialMustacheBytes() ([]byte, error) {
	return bindataRead(
		_partialMustache,
		"partial.mustache",
	)
}

func partialMustache() (*asset, error) {
	bytes, err := partialMustacheBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "partial.mustache", size: 8, mode: os.FileMode(420), modTime: time.Unix(1438094434, 0)}
	a := &asset{bytes: bytes, info:  info}
	return a, nil
}

var _test1Mustache = []byte("\x1f\x8b\x08\x00\x00\x09\x6e\x88\x00\xff\xca\x48\xcd\xc9\xc9\x57\xa8\xae\xce\x4b\xcc\x4d\xad\xad\x05\x04\x00\x00\xff\xff\x52\x6c\xe4\x12\x0e\x00\x00\x00")

func test1MustacheBytes() ([]byte, error) {
	return bindataRead(
		_test1Mustache,
		"test1.mustache",
	)
}

func test1Mustache() (*asset, error) {
	bytes, err := test1MustacheBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "test1.mustache", size: 14, mode: os.FileMode(420), modTime: time.Unix(1438094434, 0)}
	a := &asset{bytes: bytes, info:  info}
	return a, nil
}

var _test2Mustache = []byte("\x1f\x8b\x08\x00\x00\x09\x6e\x88\x00\xff\xca\x48\xcd\xc9\xc9\x57\xa8\xae\xb6\x53\x28\x48\x2c\x2a\xc9\x4c\xcc\xa9\xad\x05\x04\x00\x00\xff\xff\xc1\xad\x0a\xc0\x13\x00\x00\x00")

func test2MustacheBytes() ([]byte, error) {
	return bindataRead(
		_test2Mustache,
		"test2.mustache",
	)
}

func test2Mustache() (*asset, error) {
	bytes, err := test2MustacheBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "test2.mustache", size: 19, mode: os.FileMode(420), modTime: time.Unix(1438094434, 0)}
	a := &asset{bytes: bytes, info:  info}
	return a, nil
}

var _test3Mustache = []byte("\x1f\x8b\x08\x00\x00\x09\x6e\x88\x00\xff\xaa\xae\x56\x2e\x2d\x4e\x2d\x2a\xae\xad\xe5\xf2\xc8\x54\xa8\xae\xb6\x53\x28\x48\x2c\x2a\xc9\x4c\xcc\x01\x0a\x54\x57\xeb\x43\xe5\x00\x01\x00\x00\xff\xff\xe4\x8c\xbd\x91\x26\x00\x00\x00")

func test3MustacheBytes() ([]byte, error) {
	return bindataRead(
		_test3Mustache,
		"test3.mustache",
	)
}

func test3Mustache() (*asset, error) {
	bytes, err := test3MustacheBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "test3.mustache", size: 38, mode: os.FileMode(420), modTime: time.Unix(1438109554, 0)}
	a := &asset{bytes: bytes, info:  info}
	return a, nil
}

// Asset loads and returns the asset for the given name.
// It returns an error if the asset could not be found or
// could not be loaded.
func Asset(name string) ([]byte, error) {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[cannonicalName]; ok {
		a, err := f()
		if err != nil {
			return nil, fmt.Errorf("Asset %s can't read by error: %v", name, err)
		}
		return a.bytes, nil
	}
	return nil, fmt.Errorf("Asset %s not found", name)
}

// MustAsset is like Asset but panics when Asset would return an error.
// It simplifies safe initialization of global variables.
func MustAsset(name string) []byte {
	a, err := Asset(name)
	if (err != nil) {
		panic("asset: Asset(" + name + "): " + err.Error())
	}

	return a
}

// AssetInfo loads and returns the asset info for the given name.
// It returns an error if the asset could not be found or
// could not be loaded.
func AssetInfo(name string) (os.FileInfo, error) {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[cannonicalName]; ok {
		a, err := f()
		if err != nil {
			return nil, fmt.Errorf("AssetInfo %s can't read by error: %v", name, err)
		}
		return a.info, nil
	}
	return nil, fmt.Errorf("AssetInfo %s not found", name)
}

// AssetNames returns the names of the assets.
func AssetNames() []string {
	names := make([]string, 0, len(_bindata))
	for name := range _bindata {
		names = append(names, name)
	}
	return names
}

// _bindata is a table, holding each asset generator, mapped to its name.
var _bindata = map[string]func() (*asset, error){
	"partial.mustache": partialMustache,
	"test1.mustache": test1Mustache,
	"test2.mustache": test2Mustache,
	"test3.mustache": test3Mustache,
}

// AssetDir returns the file names below a certain
// directory embedded in the file by go-bindata.
// For example if you run go-bindata on data/... and data contains the
// following hierarchy:
//     data/
//       foo.txt
//       img/
//         a.png
//         b.png
// then AssetDir("data") would return []string{"foo.txt", "img"}
// AssetDir("data/img") would return []string{"a.png", "b.png"}
// AssetDir("foo.txt") and AssetDir("notexist") would return an error
// AssetDir("") will return []string{"data"}.
func AssetDir(name string) ([]string, error) {
	node := _bintree
	if len(name) != 0 {
		cannonicalName := strings.Replace(name, "\\", "/", -1)
		pathList := strings.Split(cannonicalName, "/")
		for _, p := range pathList {
			node = node.Children[p]
			if node == nil {
				return nil, fmt.Errorf("Asset %s not found", name)
			}
		}
	}
	if node.Func != nil {
		return nil, fmt.Errorf("Asset %s not found", name)
	}
	rv := make([]string, 0, len(node.Children))
	for childName := range node.Children {
		rv = append(rv, childName)
	}
	return rv, nil
}

type bintree struct {
	Func func() (*asset, error)
	Children map[string]*bintree
}
var _bintree = &bintree{nil, map[string]*bintree{
	"partial.mustache": &bintree{partialMustache, map[string]*bintree{
	}},
	"test1.mustache": &bintree{test1Mustache, map[string]*bintree{
	}},
	"test2.mustache": &bintree{test2Mustache, map[string]*bintree{
	}},
	"test3.mustache": &bintree{test3Mustache, map[string]*bintree{
	}},
}}

// RestoreAsset restores an asset under the given directory
func RestoreAsset(dir, name string) error {
        data, err := Asset(name)
        if err != nil {
                return err
        }
        info, err := AssetInfo(name)
        if err != nil {
                return err
        }
        err = os.MkdirAll(_filePath(dir, filepath.Dir(name)), os.FileMode(0755))
        if err != nil {
                return err
        }
        err = ioutil.WriteFile(_filePath(dir, name), data, info.Mode())
        if err != nil {
                return err
        }
        err = os.Chtimes(_filePath(dir, name), info.ModTime(), info.ModTime())
        if err != nil {
                return err
        }
        return nil
}

// RestoreAssets restores an asset under the given directory recursively
func RestoreAssets(dir, name string) error {
        children, err := AssetDir(name)
        // File
        if err != nil {
                return RestoreAsset(dir, name)
        }
        // Dir
        for _, child := range children {
                err = RestoreAssets(dir, filepath.Join(name, child))
                if err != nil {
                        return err
                }
        }
        return nil
}

func _filePath(dir, name string) string {
        cannonicalName := strings.Replace(name, "\\", "/", -1)
        return filepath.Join(append([]string{dir}, strings.Split(cannonicalName, "/")...)...)
}

